platform :ios, '8.0'
use_frameworks!

target 'SimpleWeather' do

pod ‘Mantle’
pod ‘LBBlurredImage’
pod ‘TSMessages’
pod ‘ReactiveCocoa’

end

target 'SimpleWeatherTests' do

end

target 'SimpleWeatherUITests' do

end

